# Generated by Django 5.2.16 on 2026-07-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('RESTAURANT', 'Restaurant'), ('RIDE', 'Ride')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('actioned_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('flight_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('hotel_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('restaurant_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('ride_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('decision_engine_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('decision_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
