# Generated by Django 5.2.16 on 2026-07-16 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flightservice',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'role': 'FLIGHT_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_flights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'role': 'HOTEL_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hotels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurantservice',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'role': 'RESTAURANT_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rideservice',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'role': 'RIDE_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tour',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='touritem',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.flightservice'),
        ),
        migrations.AddField(
            model_name='touritem',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.hotelservice'),
        ),
        migrations.AddField(
            model_name='touritem',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.restaurantservice'),
        ),
        migrations.AddField(
            model_name='touritem',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.rideservice'),
        ),
        migrations.AddField(
            model_name='touritem',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tours.tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customized_tours', to='tours.tourpackage'),
        ),
    ]
